### PR TITLE
Add new sizers to sizer demo, tidy up control window

### PR DESCRIPTION
**Pull request by halfer**
This PR adds a few new sizer demonstrations (I'm learning as I go!) and adds some frames to group similar controls together in the control pane.

I'm stuck with some screen redraw issues in the control window only, do you get them? I'm happy for you to merge down straight away, but feedback on that would be welcome - this will help to see whether wxPHP is viable for the projects I'd like to use it for (I don't want to box myself in with something that turns out not to be rigorously stable, given that wxWidgets doesn't have a wide PHP userbase).

I get the redraw issues around 20% of the time, and clicking in the demo window (so the control window loses focus) forces a redraw and "fixes" it.

### CODE REVIEW

**Comment by jgmdev** [comment]
I ran and took a look at code and everything seems to be rendering properly, Im running xfce and wxWidgets compiled against gtk3 if I recall correctly (the spinner looks like gtk3 style):
controller
demo window

The only issue on my end is that I have increased the default font size of the system:
controller issue

So I would advise to set the help control proportion to 1:
```
-$sizer->Add($this->helpCtrl, 0, wxLEFT + wxRIGHT + wxBOTTOM + wxEXPAND, 8);
+$sizer->Add($this->helpCtrl, 1, wxLEFT + wxRIGHT + wxBOTTOM + wxEXPAND, 8);
```
and to enable resizing of the controller window.

**Comment by halfer** [comment]
Ah, that's not the redraw issue I get, but thanks for flagging that. I will dig into that. I don't know how "control proportions" work but happy to make the change you suggest. The vertical dropdown looks a bit squashed as well. I'll modify the sys font size to test.

Your rendering of the Sizer Demo window is odd - those elements should have a variety of different heights, but they are all the same for you.

**Comment by halfer** [comment]
Give that a go - that seems to have fixed a lot more sizing issues. All controls except for the help text are now auto-sizing. The help text uses an initial recommended width, and then if the window is made wider, this is used for the new width (minus border space). This allows the control to wrap whilst not recommending excessively large widths.

I still get the redraw problems that I initially referred to, but IMO this can merge down and I'll look at them as a low priority at another time - I am pretty sure it is caused by wrapping in the text control, and it may just be prudent to swap this with an HTML control.

**Comment by halfer** [comment]
Great, thanks!

**Pull request merged**
