### PR TITLE
Improvements to interface_generator.php

### PR DESCRIPTION
**Pull request by Yogarine**
I plan to do some prototyping with wxphp, but I first wanted to have proper autocompletion and type checking in PhpStorm.
So I modified interface_generator.php with the following goals in mind:
- Creating proper facades of wxWidgets' overloaded functions.
- Type annotations which are as specific as possible.
- Defining the constant with proper values.

So what I did more specifically:
- Combine the different parameter names of overloaded methods by combining them from the different definitions
- Combine the different parameter types of overloaded methods
- Combine the default values for overloaded methods as well as possible
- Also combine the annotations in the PHPdocs as well as posisble
- Make sure the constants contain properly cleaned up values.
- Added __construct() aliases for the constructors
- Prefix the methods with "public"
- Remove the & for all the params of objects since objects are always by reference in PHP.

The code which is now generated creates stubs that nicely match the wxWidget interface as good as possible, while attempting as well as possible to give decent type hinting and context.

### CODE REVIEW

**Comment by jgmdev** [comment]
Any news on the improvements to the intarface generator? I'm going to do a v3.0.2.0 release and would like to update interface file for it.

**Comment by Yogarine** [comment]
Sorry, I didn't have the time to work on this since then. Also it was working for me at the time and since then I've put my wxPHP-based project on hold while working on other things, and I have no time.

I will have another look at it at some point but not soon. I simply don't have the time, or even e local checkout the code for that matter.

However what I personally suggest is that you just take a simple look what is causing the parse errors, merge this and then fix those issues, and just stick with my changes because:

1. I believe the & was actually giving warnings in PhpStorm, and either way when you provide an object to a function you can always expect it to be modified. However the main issue was I thought the warnings in PhpStorm were ugly.

2. Having the public keyword there is just for completeness... It doesn't really matter that much in terms of size and the parsing overhead is negligible and only incurred once when the file is read anyway.

3. The whole idea of generating a stubs file is that you shouldn't have to edit it and just get proper autocompletion and inspection. Besides, what if I decide I want to use two variations of a method? My solution attempts to adapt the overloaded functions from wxWidgets in an understandable way.

As for 4. feel free to revert the related change. (The default for the switch at the end of get_argument_declaration()). You could also make it smarter so it only sets the type if the default value is null or if there is no default value.

**Comment by rtrzebinski** [comment]
@Yogarine Thank you for your contribution! Interface file I generated from your version is way better than the default one. Still not complete and having some issues but it's a step into the right direction.

I'd like to help you finishing interface generator. I believe that lack of autocompletion is a big issue, and a lot of people might be discouraged because of it. This task should have high priority. Good IDE helper is a must, coding without it is a massive pain - we must do that if we want people to use wxPHP.

@jgmdev do you think we could merge this change, and start other changes including great job done by @Yogarine ? I will then start new branch, and make required changes on it.

**Comment by jgmdev** [comment]
Done!

**Pull request merged**
